databases:
  - name: cinefydb
    plan: free
    databaseName: Cinefy-DB
    user: cinefy_admin

services:
  - type: web
    name: cinefy-web
    runtime: python3
    buildCommand: "cd Backend/cinefy && chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn Backend.cinefy.cinefy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinefydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"