services:
  - type: web
    name: cinefy-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cinefy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinefy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
  - type: postgres
    name: cinefy-db