# Generated by Django 5.0.4 on 2024-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('release_year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=100)),
                ('casts', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
                ('description', models.TextField(max_length=5000)),
                ('poster_image', models.ImageField(upload_to='posters/')),
                ('trailer_video', models.URLField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
